version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cv-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1nz5lni7obqvw"
s3_prefix = "cv-app"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
parameter_overrides = "BucketName=\"anebz\""
